spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olx
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 8a6149a90372c5
    password: a8c610325a9776
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secret-key: d12ef765cf731897283ba2845488b8e41f8b10d275268249d80d9419a46d315f
    expiration-mills: 60000

frontend:
  url: http://localhost:8080/auth/verify?token=
  support-email: pdp_support@gmail.uz